{
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "HdgyQXHDVg5P"
      },
      "source": [
        "# Implementing market basket insights\n",
        "\n",
        "AI-Dataset Loading And Preprocessing\n",
        "\n",
        "## Step 1: Data Loading\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "07xmzKLmVg5a"
      },
      "outputs": [],
      "source": [
        "#Loading neccesary packages\n",
        "import numpy as np\n",
        "import pandas as pd\n",
        "from mlxtend.frequent_patterns import apriori\n",
        "from mlxtend.frequent_patterns import association_rules"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "bTJqHwUZVg5f",
        "outputId": "a6bf15ca-8ed8-4aff-c5b1-29869df98358"
      },
      "outputs": [
        {
          "data": {
            "text/html": [
              "<div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>InvoiceNo</th>\n",
              "      <th>StockCode</th>\n",
              "      <th>Description</th>\n",
              "      <th>Quantity</th>\n",
              "      <th>InvoiceDate</th>\n",
              "      <th>UnitPrice</th>\n",
              "      <th>CustomerID</th>\n",
              "      <th>Country</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>536365</td>\n",
              "      <td>85123A</td>\n",
              "      <td>WHITE HANGING HEART T-LIGHT HOLDER</td>\n",
              "      <td>6</td>\n",
              "      <td>2010-12-01 08:26:00</td>\n",
              "      <td>2.55</td>\n",
              "      <td>17850.0</td>\n",
              "      <td>United Kingdom</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1</th>\n",
              "      <td>536365</td>\n",
              "      <td>71053</td>\n",
              "      <td>WHITE METAL LANTERN</td>\n",
              "      <td>6</td>\n",
              "      <td>2010-12-01 08:26:00</td>\n",
              "      <td>3.39</td>\n",
              "      <td>17850.0</td>\n",
              "      <td>United Kingdom</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2</th>\n",
              "      <td>536365</td>\n",
              "      <td>84406B</td>\n",
              "      <td>CREAM CUPID HEARTS COAT HANGER</td>\n",
              "      <td>8</td>\n",
              "      <td>2010-12-01 08:26:00</td>\n",
              "      <td>2.75</td>\n",
              "      <td>17850.0</td>\n",
              "      <td>United Kingdom</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>3</th>\n",
              "      <td>536365</td>\n",
              "      <td>84029G</td>\n",
              "      <td>KNITTED UNION FLAG HOT WATER BOTTLE</td>\n",
              "      <td>6</td>\n",
              "      <td>2010-12-01 08:26:00</td>\n",
              "      <td>3.39</td>\n",
              "      <td>17850.0</td>\n",
              "      <td>United Kingdom</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>4</th>\n",
              "      <td>536365</td>\n",
              "      <td>84029E</td>\n",
              "      <td>RED WOOLLY HOTTIE WHITE HEART.</td>\n",
              "      <td>6</td>\n",
              "      <td>2010-12-01 08:26:00</td>\n",
              "      <td>3.39</td>\n",
              "      <td>17850.0</td>\n",
              "      <td>United Kingdom</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "</div>"
            ],
            "text/plain": [
              "  InvoiceNo StockCode                          Description  Quantity  \\\n",
              "0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   \n",
              "1    536365     71053                  WHITE METAL LANTERN         6   \n",
              "2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   \n",
              "3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   \n",
              "4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   \n",
              "\n",
              "          InvoiceDate  UnitPrice  CustomerID         Country  \n",
              "0 2010-12-01 08:26:00       2.55     17850.0  United Kingdom  \n",
              "1 2010-12-01 08:26:00       3.39     17850.0  United Kingdom  \n",
              "2 2010-12-01 08:26:00       2.75     17850.0  United Kingdom  \n",
              "3 2010-12-01 08:26:00       3.39     17850.0  United Kingdom  \n",
              "4 2010-12-01 08:26:00       3.39     17850.0  United Kingdom  "
            ]
          },
          "execution_count": 79,
          "metadata": {},
          "output_type": "execute_result"
        }
      ],
      "source": [
        "#Reading Data From Web\n",
        "#myretaildata = pd.read_excel('http://archive.ics.uci.edu/ml/machine-learning-databases/00352/Online%20Retail.xlsx')\n",
        "myretaildata.head()"
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "# Explanation/Documentation(Step 1)\n",
        "\n",
        "\n",
        "\n",
        "*   The first step is to gather transaction data, which typically includes information about what items were purchased together in each transaction. This data can be in the form of a database, spreadsheet, or any other structured format.\n",
        "*  You need to load the data into a suitable data structure, often a data frame or table. Tools like Python's Pandas or R can be used for this purpose. The data should have rows representing transactions and columns representing items or products.\n",
        "\n"
      ],
      "metadata": {
        "id": "tKAQY6itX1BQ"
      }
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "cSAn186AVg5j"
      },
      "source": [
        "#Step 2: Data Preprocessing"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "osPhvOqZVg5o",
        "outputId": "c613c897-958e-4bea-b7d0-4d989ff3f493"
      },
      "outputs": [
        {
          "data": {
            "text/html": [
              "<div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>InvoiceNo</th>\n",
              "      <th>StockCode</th>\n",
              "      <th>Description</th>\n",
              "      <th>Quantity</th>\n",
              "      <th>InvoiceDate</th>\n",
              "      <th>UnitPrice</th>\n",
              "      <th>CustomerID</th>\n",
              "      <th>Country</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>536365</td>\n",
              "      <td>85123A</td>\n",
              "      <td>WHITE HANGING HEART T-LIGHT HOLDER</td>\n",
              "      <td>6</td>\n",
              "      <td>2010-12-01 08:26:00</td>\n",
              "      <td>2.55</td>\n",
              "      <td>17850.0</td>\n",
              "      <td>United Kingdom</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1</th>\n",
              "      <td>536365</td>\n",
              "      <td>71053</td>\n",
              "      <td>WHITE METAL LANTERN</td>\n",
              "      <td>6</td>\n",
              "      <td>2010-12-01 08:26:00</td>\n",
              "      <td>3.39</td>\n",
              "      <td>17850.0</td>\n",
              "      <td>United Kingdom</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2</th>\n",
              "      <td>536365</td>\n",
              "      <td>84406B</td>\n",
              "      <td>CREAM CUPID HEARTS COAT HANGER</td>\n",
              "      <td>8</td>\n",
              "      <td>2010-12-01 08:26:00</td>\n",
              "      <td>2.75</td>\n",
              "      <td>17850.0</td>\n",
              "      <td>United Kingdom</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>3</th>\n",
              "      <td>536365</td>\n",
              "      <td>84029G</td>\n",
              "      <td>KNITTED UNION FLAG HOT WATER BOTTLE</td>\n",
              "      <td>6</td>\n",
              "      <td>2010-12-01 08:26:00</td>\n",
              "      <td>3.39</td>\n",
              "      <td>17850.0</td>\n",
              "      <td>United Kingdom</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>4</th>\n",
              "      <td>536365</td>\n",
              "      <td>84029E</td>\n",
              "      <td>RED WOOLLY HOTTIE WHITE HEART.</td>\n",
              "      <td>6</td>\n",
              "      <td>2010-12-01 08:26:00</td>\n",
              "      <td>3.39</td>\n",
              "      <td>17850.0</td>\n",
              "      <td>United Kingdom</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "</div>"
            ],
            "text/plain": [
              "  InvoiceNo StockCode                          Description  Quantity  \\\n",
              "0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   \n",
              "1    536365     71053                  WHITE METAL LANTERN         6   \n",
              "2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   \n",
              "3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   \n",
              "4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   \n",
              "\n",
              "          InvoiceDate  UnitPrice  CustomerID         Country  \n",
              "0 2010-12-01 08:26:00       2.55     17850.0  United Kingdom  \n",
              "1 2010-12-01 08:26:00       3.39     17850.0  United Kingdom  \n",
              "2 2010-12-01 08:26:00       2.75     17850.0  United Kingdom  \n",
              "3 2010-12-01 08:26:00       3.39     17850.0  United Kingdom  \n",
              "4 2010-12-01 08:26:00       3.39     17850.0  United Kingdom  "
            ]
          },
          "execution_count": 80,
          "metadata": {},
          "output_type": "execute_result"
        }
      ],
      "source": [
        "#Data Cleaning\n",
        "myretaildata['Description'] = myretaildata['Description'].str.strip() #removes spaces from beginning and end\n",
        "myretaildata.dropna(axis=0, subset=['InvoiceNo'], inplace=True) #removes duplicate invoice\n",
        "myretaildata['InvoiceNo'] = myretaildata['InvoiceNo'].astype('str') #converting invoice number to be string\n",
        "myretaildata = myretaildata[~myretaildata['InvoiceNo'].str.contains('C')] #remove the credit transactions\n",
        "myretaildata.head()"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "lCJI5slaVg5q",
        "outputId": "65ecec81-080e-41c0-ebe8-916f1acaf5cc"
      },
      "outputs": [
        {
          "data": {
            "text/plain": [
              "United Kingdom          487622\n",
              "Germany                   9042\n",
              "France                    8408\n",
              "EIRE                      7894\n",
              "Spain                     2485\n",
              "Netherlands               2363\n",
              "Belgium                   2031\n",
              "Switzerland               1967\n",
              "Portugal                  1501\n",
              "Australia                 1185\n",
              "Norway                    1072\n",
              "Italy                      758\n",
              "Channel Islands            748\n",
              "Finland                    685\n",
              "Cyprus                     614\n",
              "Sweden                     451\n",
              "Unspecified                446\n",
              "Austria                    398\n",
              "Denmark                    380\n",
              "Poland                     330\n",
              "Japan                      321\n",
              "Israel                     295\n",
              "Hong Kong                  284\n",
              "Singapore                  222\n",
              "Iceland                    182\n",
              "USA                        179\n",
              "Canada                     151\n",
              "Greece                     145\n",
              "Malta                      112\n",
              "United Arab Emirates        68\n",
              "European Community          60\n",
              "RSA                         58\n",
              "Lebanon                     45\n",
              "Lithuania                   35\n",
              "Brazil                      32\n",
              "Czech Republic              25\n",
              "Bahrain                     18\n",
              "Saudi Arabia                 9\n",
              "Name: Country, dtype: int64"
            ]
          },
          "execution_count": 83,
          "metadata": {},
          "output_type": "execute_result"
        }
      ],
      "source": [
        "myretaildata['Country'].value_counts()\n",
        "#myretaildata.shape"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "mNBwU75XVg5s"
      },
      "outputs": [],
      "source": [
        "#Separating transactions for Germany\n",
        "mybasket = (myretaildata[myretaildata['Country'] ==\"Germany\"]\n",
        "          .groupby(['InvoiceNo', 'Description'])['Quantity']\n",
        "          .sum().unstack().reset_index().fillna(0)\n",
        "          .set_index('InvoiceNo'))"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "mwYZxvjQVg5u",
        "outputId": "21905e16-5573-4f28-c60e-90f653b57fe6"
      },
      "outputs": [
        {
          "data": {
            "text/html": [
              "<div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th>Description</th>\n",
              "      <th>10 COLOUR SPACEBOY PEN</th>\n",
              "      <th>12 COLOURED PARTY BALLOONS</th>\n",
              "      <th>12 IVORY ROSE PEG PLACE SETTINGS</th>\n",
              "      <th>12 MESSAGE CARDS WITH ENVELOPES</th>\n",
              "      <th>12 PENCIL SMALL TUBE WOODLAND</th>\n",
              "      <th>12 PENCILS SMALL TUBE RED RETROSPOT</th>\n",
              "      <th>12 PENCILS SMALL TUBE SKULL</th>\n",
              "      <th>12 PENCILS TALL TUBE POSY</th>\n",
              "      <th>12 PENCILS TALL TUBE RED RETROSPOT</th>\n",
              "      <th>12 PENCILS TALL TUBE SKULLS</th>\n",
              "      <th>...</th>\n",
              "      <th>YULETIDE IMAGES GIFT WRAP SET</th>\n",
              "      <th>ZINC  HEART T-LIGHT HOLDER</th>\n",
              "      <th>ZINC  STAR T-LIGHT HOLDER</th>\n",
              "      <th>ZINC BOX SIGN HOME</th>\n",
              "      <th>ZINC FOLKART SLEIGH BELLS</th>\n",
              "      <th>ZINC HEART LATTICE T-LIGHT HOLDER</th>\n",
              "      <th>ZINC METAL HEART DECORATION</th>\n",
              "      <th>ZINC T-LIGHT HOLDER STAR LARGE</th>\n",
              "      <th>ZINC T-LIGHT HOLDER STARS SMALL</th>\n",
              "      <th>ZINC WILLIE WINKIE  CANDLE STICK</th>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>InvoiceNo</th>\n",
              "      <th></th>\n",
              "      <th></th>\n",
              "      <th></th>\n",
              "      <th></th>\n",
              "      <th></th>\n",
              "      <th></th>\n",
              "      <th></th>\n",
              "      <th></th>\n",
              "      <th></th>\n",
              "      <th></th>\n",
              "      <th></th>\n",
              "      <th></th>\n",
              "      <th></th>\n",
              "      <th></th>\n",
              "      <th></th>\n",
              "      <th></th>\n",
              "      <th></th>\n",
              "      <th></th>\n",
              "      <th></th>\n",
              "      <th></th>\n",
              "      <th></th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>536527</th>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>...</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>536840</th>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>...</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>536861</th>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>...</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>536967</th>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>...</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>536983</th>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>...</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "<p>5 rows × 1695 columns</p>\n",
              "</div>"
            ],
            "text/plain": [
              "Description  10 COLOUR SPACEBOY PEN  12 COLOURED PARTY BALLOONS  \\\n",
              "InvoiceNo                                                         \n",
              "536527                          0.0                         0.0   \n",
              "536840                          0.0                         0.0   \n",
              "536861                          0.0                         0.0   \n",
              "536967                          0.0                         0.0   \n",
              "536983                          0.0                         0.0   \n",
              "\n",
              "Description  12 IVORY ROSE PEG PLACE SETTINGS  \\\n",
              "InvoiceNo                                       \n",
              "536527                                    0.0   \n",
              "536840                                    0.0   \n",
              "536861                                    0.0   \n",
              "536967                                    0.0   \n",
              "536983                                    0.0   \n",
              "\n",
              "Description  12 MESSAGE CARDS WITH ENVELOPES  12 PENCIL SMALL TUBE WOODLAND  \\\n",
              "InvoiceNo                                                                     \n",
              "536527                                   0.0                            0.0   \n",
              "536840                                   0.0                            0.0   \n",
              "536861                                   0.0                            0.0   \n",
              "536967                                   0.0                            0.0   \n",
              "536983                                   0.0                            0.0   \n",
              "\n",
              "Description  12 PENCILS SMALL TUBE RED RETROSPOT  12 PENCILS SMALL TUBE SKULL  \\\n",
              "InvoiceNo                                                                       \n",
              "536527                                       0.0                          0.0   \n",
              "536840                                       0.0                          0.0   \n",
              "536861                                       0.0                          0.0   \n",
              "536967                                       0.0                          0.0   \n",
              "536983                                       0.0                          0.0   \n",
              "\n",
              "Description  12 PENCILS TALL TUBE POSY  12 PENCILS TALL TUBE RED RETROSPOT  \\\n",
              "InvoiceNo                                                                    \n",
              "536527                             0.0                                 0.0   \n",
              "536840                             0.0                                 0.0   \n",
              "536861                             0.0                                 0.0   \n",
              "536967                             0.0                                 0.0   \n",
              "536983                             0.0                                 0.0   \n",
              "\n",
              "Description  12 PENCILS TALL TUBE SKULLS  ...  YULETIDE IMAGES GIFT WRAP SET  \\\n",
              "InvoiceNo                                 ...                                  \n",
              "536527                               0.0  ...                            0.0   \n",
              "536840                               0.0  ...                            0.0   \n",
              "536861                               0.0  ...                            0.0   \n",
              "536967                               0.0  ...                            0.0   \n",
              "536983                               0.0  ...                            0.0   \n",
              "\n",
              "Description  ZINC  HEART T-LIGHT HOLDER  ZINC  STAR T-LIGHT HOLDER  \\\n",
              "InvoiceNo                                                            \n",
              "536527                              0.0                        0.0   \n",
              "536840                              0.0                        0.0   \n",
              "536861                              0.0                        0.0   \n",
              "536967                              0.0                        0.0   \n",
              "536983                              0.0                        0.0   \n",
              "\n",
              "Description  ZINC BOX SIGN HOME  ZINC FOLKART SLEIGH BELLS  \\\n",
              "InvoiceNo                                                    \n",
              "536527                      0.0                        0.0   \n",
              "536840                      0.0                        0.0   \n",
              "536861                      0.0                        0.0   \n",
              "536967                      0.0                        0.0   \n",
              "536983                      0.0                        0.0   \n",
              "\n",
              "Description  ZINC HEART LATTICE T-LIGHT HOLDER  ZINC METAL HEART DECORATION  \\\n",
              "InvoiceNo                                                                     \n",
              "536527                                     0.0                          0.0   \n",
              "536840                                     0.0                          0.0   \n",
              "536861                                     0.0                          0.0   \n",
              "536967                                     0.0                          0.0   \n",
              "536983                                     0.0                          0.0   \n",
              "\n",
              "Description  ZINC T-LIGHT HOLDER STAR LARGE  ZINC T-LIGHT HOLDER STARS SMALL  \\\n",
              "InvoiceNo                                                                      \n",
              "536527                                  0.0                              0.0   \n",
              "536840                                  0.0                              0.0   \n",
              "536861                                  0.0                              0.0   \n",
              "536967                                  0.0                              0.0   \n",
              "536983                                  0.0                              0.0   \n",
              "\n",
              "Description  ZINC WILLIE WINKIE  CANDLE STICK  \n",
              "InvoiceNo                                      \n",
              "536527                                    0.0  \n",
              "536840                                    0.0  \n",
              "536861                                    0.0  \n",
              "536967                                    0.0  \n",
              "536983                                    0.0  \n",
              "\n",
              "[5 rows x 1695 columns]"
            ]
          },
          "execution_count": 85,
          "metadata": {},
          "output_type": "execute_result"
        }
      ],
      "source": [
        "#viewing transaction basket\n",
        "mybasket.head()"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "VDRCXlU7Vg5w"
      },
      "outputs": [],
      "source": [
        "#converting all positive vaues to 1 and everything else to 0\n",
        "def my_encode_units(x):\n",
        "    if x <= 0:\n",
        "        return 0\n",
        "    if x >= 1:\n",
        "        return 1\n",
        "\n",
        "my_basket_sets = mybasket.applymap(my_encode_units)\n",
        "my_basket_sets.drop('POSTAGE', inplace=True, axis=1) #Remove \"postage\" as an item"
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "# Explanation/Documentation(Step 2)\n",
        "\n",
        "*  Data Collection: The first step is to gather transaction data, which typically includes information about what items were purchased together in each transaction. This data can be in the form of a database, spreadsheet, or any other structured format.\n",
        "\n",
        "\n",
        "\n",
        "*  Data Loading: You need to load the data into a suitable data structure, often a data frame or table. Tools like Python's Pandas or R can be used for this purpose. The data should have rows representing transactions and columns representing items or products.\n",
        "\n",
        "\n",
        "*   Cleaning Data: Remove any irrelevant or erroneous information. Check for missing values, duplicate entries, or inconsistent data.\n",
        "\n",
        "\n",
        "*  Transaction Encoding: In order to perform market basket analysis, you need to encode the data into a binary format where each row represents a transaction, and each column corresponds to an item. A '1' indicates the item was bought in that transaction, and '0' indicates it was not.\n",
        "\n",
        "*   Support Threshold: You often set a minimum support threshold, which is the minimum proportion of transactions in which an itemset (a combination of items) must appear to be considered frequent. This helps in reducing the number of itemsets to analyze.\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n"
      ],
      "metadata": {
        "id": "UFqP5m-9YXSK"
      }
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "BgxlP-utVg5y"
      },
      "source": [
        "# Step 3: Initial Analysis"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "FxtMjpGnVg54"
      },
      "outputs": [],
      "source": [
        "#Generatig frequent itemsets\n",
        "my_frequent_itemsets = apriori(my_basket_sets, min_support=0.07, use_colnames=True)"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "ehAPoPfBVg57"
      },
      "outputs": [],
      "source": [
        "#generating rules\n",
        "my_rules = association_rules(my_frequent_itemsets, metric=\"lift\", min_threshold=1)"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "alwb5XozVg58",
        "outputId": "e2ad3370-b304-4c18-d5fa-dc0f7542ed1d"
      },
      "outputs": [
        {
          "data": {
            "text/html": [
              "<div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>antecedents</th>\n",
              "      <th>consequents</th>\n",
              "      <th>antecedent support</th>\n",
              "      <th>consequent support</th>\n",
              "      <th>support</th>\n",
              "      <th>confidence</th>\n",
              "      <th>lift</th>\n",
              "      <th>leverage</th>\n",
              "      <th>conviction</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>(PLASTERS IN TIN WOODLAND ANIMALS)</td>\n",
              "      <td>(ROUND SNACK BOXES SET OF4 WOODLAND)</td>\n",
              "      <td>0.137856</td>\n",
              "      <td>0.245077</td>\n",
              "      <td>0.074398</td>\n",
              "      <td>0.539683</td>\n",
              "      <td>2.202098</td>\n",
              "      <td>0.040613</td>\n",
              "      <td>1.640006</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1</th>\n",
              "      <td>(ROUND SNACK BOXES SET OF4 WOODLAND)</td>\n",
              "      <td>(PLASTERS IN TIN WOODLAND ANIMALS)</td>\n",
              "      <td>0.245077</td>\n",
              "      <td>0.137856</td>\n",
              "      <td>0.074398</td>\n",
              "      <td>0.303571</td>\n",
              "      <td>2.202098</td>\n",
              "      <td>0.040613</td>\n",
              "      <td>1.237951</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2</th>\n",
              "      <td>(ROUND SNACK BOXES SET OF 4 FRUITS)</td>\n",
              "      <td>(ROUND SNACK BOXES SET OF4 WOODLAND)</td>\n",
              "      <td>0.157549</td>\n",
              "      <td>0.245077</td>\n",
              "      <td>0.131291</td>\n",
              "      <td>0.833333</td>\n",
              "      <td>3.400298</td>\n",
              "      <td>0.092679</td>\n",
              "      <td>4.529540</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>3</th>\n",
              "      <td>(ROUND SNACK BOXES SET OF4 WOODLAND)</td>\n",
              "      <td>(ROUND SNACK BOXES SET OF 4 FRUITS)</td>\n",
              "      <td>0.245077</td>\n",
              "      <td>0.157549</td>\n",
              "      <td>0.131291</td>\n",
              "      <td>0.535714</td>\n",
              "      <td>3.400298</td>\n",
              "      <td>0.092679</td>\n",
              "      <td>1.814509</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>4</th>\n",
              "      <td>(SPACEBOY LUNCH BOX)</td>\n",
              "      <td>(ROUND SNACK BOXES SET OF4 WOODLAND)</td>\n",
              "      <td>0.102845</td>\n",
              "      <td>0.245077</td>\n",
              "      <td>0.070022</td>\n",
              "      <td>0.680851</td>\n",
              "      <td>2.778116</td>\n",
              "      <td>0.044817</td>\n",
              "      <td>2.365427</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>5</th>\n",
              "      <td>(ROUND SNACK BOXES SET OF4 WOODLAND)</td>\n",
              "      <td>(SPACEBOY LUNCH BOX)</td>\n",
              "      <td>0.245077</td>\n",
              "      <td>0.102845</td>\n",
              "      <td>0.070022</td>\n",
              "      <td>0.285714</td>\n",
              "      <td>2.778116</td>\n",
              "      <td>0.044817</td>\n",
              "      <td>1.256018</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "</div>"
            ],
            "text/plain": [
              "                            antecedents                           consequents  \\\n",
              "0    (PLASTERS IN TIN WOODLAND ANIMALS)  (ROUND SNACK BOXES SET OF4 WOODLAND)   \n",
              "1  (ROUND SNACK BOXES SET OF4 WOODLAND)    (PLASTERS IN TIN WOODLAND ANIMALS)   \n",
              "2   (ROUND SNACK BOXES SET OF 4 FRUITS)  (ROUND SNACK BOXES SET OF4 WOODLAND)   \n",
              "3  (ROUND SNACK BOXES SET OF4 WOODLAND)   (ROUND SNACK BOXES SET OF 4 FRUITS)   \n",
              "4                  (SPACEBOY LUNCH BOX)  (ROUND SNACK BOXES SET OF4 WOODLAND)   \n",
              "5  (ROUND SNACK BOXES SET OF4 WOODLAND)                  (SPACEBOY LUNCH BOX)   \n",
              "\n",
              "   antecedent support  consequent support   support  confidence      lift  \\\n",
              "0            0.137856            0.245077  0.074398    0.539683  2.202098   \n",
              "1            0.245077            0.137856  0.074398    0.303571  2.202098   \n",
              "2            0.157549            0.245077  0.131291    0.833333  3.400298   \n",
              "3            0.245077            0.157549  0.131291    0.535714  3.400298   \n",
              "4            0.102845            0.245077  0.070022    0.680851  2.778116   \n",
              "5            0.245077            0.102845  0.070022    0.285714  2.778116   \n",
              "\n",
              "   leverage  conviction  \n",
              "0  0.040613    1.640006  \n",
              "1  0.040613    1.237951  \n",
              "2  0.092679    4.529540  \n",
              "3  0.092679    1.814509  \n",
              "4  0.044817    2.365427  \n",
              "5  0.044817    1.256018  "
            ]
          },
          "execution_count": 89,
          "metadata": {},
          "output_type": "execute_result"
        }
      ],
      "source": [
        "#viewing top 100 rules\n",
        "my_rules.head(100)"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "2_eU8sc5Vg5-"
      },
      "source": [
        "# Making reecommendations"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "gzyGUpLnVg5-",
        "outputId": "7a6868bb-c615-4449-c715-5726888bf756"
      },
      "outputs": [
        {
          "data": {
            "text/plain": [
              "112"
            ]
          },
          "execution_count": 90,
          "metadata": {},
          "output_type": "execute_result"
        }
      ],
      "source": [
        "my_basket_sets['ROUND SNACK BOXES SET OF4 WOODLAND'].sum()"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "RvCRlZB2Vg5_",
        "outputId": "cabf97dc-e717-4800-faac-e80ac510a6e4"
      },
      "outputs": [
        {
          "data": {
            "text/plain": [
              "47"
            ]
          },
          "execution_count": 91,
          "metadata": {},
          "output_type": "execute_result"
        }
      ],
      "source": [
        "my_basket_sets['SPACEBOY LUNCH BOX'].sum()\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "fm1qfoRjVg6A",
        "outputId": "f7450fea-577a-4bbc-94f2-c8802127b66d"
      },
      "outputs": [
        {
          "data": {
            "text/html": [
              "<div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>antecedents</th>\n",
              "      <th>consequents</th>\n",
              "      <th>antecedent support</th>\n",
              "      <th>consequent support</th>\n",
              "      <th>support</th>\n",
              "      <th>confidence</th>\n",
              "      <th>lift</th>\n",
              "      <th>leverage</th>\n",
              "      <th>conviction</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>2</th>\n",
              "      <td>(ROUND SNACK BOXES SET OF 4 FRUITS)</td>\n",
              "      <td>(ROUND SNACK BOXES SET OF4 WOODLAND)</td>\n",
              "      <td>0.157549</td>\n",
              "      <td>0.245077</td>\n",
              "      <td>0.131291</td>\n",
              "      <td>0.833333</td>\n",
              "      <td>3.400298</td>\n",
              "      <td>0.092679</td>\n",
              "      <td>4.529540</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>3</th>\n",
              "      <td>(ROUND SNACK BOXES SET OF4 WOODLAND)</td>\n",
              "      <td>(ROUND SNACK BOXES SET OF 4 FRUITS)</td>\n",
              "      <td>0.245077</td>\n",
              "      <td>0.157549</td>\n",
              "      <td>0.131291</td>\n",
              "      <td>0.535714</td>\n",
              "      <td>3.400298</td>\n",
              "      <td>0.092679</td>\n",
              "      <td>1.814509</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "</div>"
            ],
            "text/plain": [
              "                            antecedents                           consequents  \\\n",
              "2   (ROUND SNACK BOXES SET OF 4 FRUITS)  (ROUND SNACK BOXES SET OF4 WOODLAND)   \n",
              "3  (ROUND SNACK BOXES SET OF4 WOODLAND)   (ROUND SNACK BOXES SET OF 4 FRUITS)   \n",
              "\n",
              "   antecedent support  consequent support   support  confidence      lift  \\\n",
              "2            0.157549            0.245077  0.131291    0.833333  3.400298   \n",
              "3            0.245077            0.157549  0.131291    0.535714  3.400298   \n",
              "\n",
              "   leverage  conviction  \n",
              "2  0.092679    4.529540  \n",
              "3  0.092679    1.814509  "
            ]
          },
          "execution_count": 92,
          "metadata": {},
          "output_type": "execute_result"
        }
      ],
      "source": [
        "#Filtering rules based on condition\n",
        "my_rules[ (my_rules['lift'] >= 3) &\n",
        "       (my_rules['confidence'] >= 0.3) ]"
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "# Explanation/Documentation(Step 3)\n",
        "\n",
        "\n",
        "* Market Basket Analysis: Once your data is preprocessed, you can apply market\n",
        " basket analysis techniques such as Apriori or FP-Growth to discover frequent itemsets and association rules. These rules show relationships between items and provide insights like \"People who buy A also buy B.\"\n",
        "\n",
        "* Insights and Action: Analyze the association rules and frequent itemsets to gain insights into purchasing patterns. You might discover items that are often bought together or find opportunities for product placement, promotions, or recommendations.\n",
        "\n",
        "* Visualization: You can visualize your insights using charts, graphs, or other visualization techniques to make it easier to understand and share with stakeholders.\n",
        "\n",
        "* Iterate: Market basket analysis is an iterative process. You may need to fine-tune your support and confidence thresholds, try different algorithms, or experiment with different data subsets to get meaningful insights.\n",
        "\n"
      ],
      "metadata": {
        "id": "NnrwglNXXSig"
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "RAJESH KANNAN\n",
        "\n",
        "NANDHA COLLEGE OF TECHNOLOGY\n",
        "\n",
        "22.10.2023"
      ],
      "metadata": {
        "id": "H8EOyt7AWd90"
      }
    }
  ],
  "metadata": {
    "kernelspec": {
      "display_name": "Python 3",
      "language": "python",
      "name": "python3"
    },
    "language_info": {
      "codemirror_mode": {
        "name": "ipython",
        "version": 3
      },
      "file_extension": ".py",
      "mimetype": "text/x-python",
      "name": "python",
      "nbconvert_exporter": "python",
      "pygments_lexer": "ipython3",
      "version": "3.7.3"
    },
    "colab": {
      "provenance": []
    }
  },
  "nbformat": 4,
  "nbformat_minor": 0
}
